# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

python:
  - "3.7"

# Install the codecov pip dependency
install:
  - pip install codecov pytest

# Run the unit test 
  - pytest --cov=./