# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

python:
  - "3.7"

# Install the codecov pip dependency and my own lib for testing
# pytest-cov is not enough for travis virtual env. It will report codecov not found.
# codecov is still required per https://github.com/codecov/codecov-python/blob/master/README.md#ci-providers
install:
  - pip install pytest-cov pytest codecov
  - python setup.py bdist_wheel
  - pip install dist/kickcmd-*.whl

# And run the pytest with codecov.
script:
  - python -m pytest --cov-report term --cov=kickcmd

after_success:
  - codecov

env:
  - CODECOV_TOKEN="70124566-6be5-4aba-a225-636bd9c1904a"